const __APP_THEME_STYLESHEET_CONTAINER__ =
  "__APP_THEME_STYLESHEET_CONTAINER__" as const;

const __APP_GLOBAL_THEME_CENTER__ = "__APP_GLOBAL_THEME_CENTER__" as const;

const ROOT_ELEMENT_ID = "root" as const;

const THEME_INFO = "THEME_INFO_" as const;

export {
  __APP_THEME_STYLESHEET_CONTAINER__,
  __APP_GLOBAL_THEME_CENTER__,
  ROOT_ELEMENT_ID,
  THEME_INFO,
};
