/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function wrap(userRootPath: string, userLanguagePath: string, userInclude: Array<string>, userExclude: Array<string>): void
